//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DotnetProjectHostingExtensions
    {
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREDOTNETPROJECT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Polyglot app hosts use the internal addDotnetProject dispatcher export.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DotnetProjectResource> AddDotnetProject(this IDistributedApplicationBuilder builder, string name, string path, System.Action<ProjectResourceOptions> configure) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIREDOTNETPROJECT001", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Polyglot app hosts use the internal addDotnetProject dispatcher export.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DotnetProjectResource> AddDotnetProject(this IDistributedApplicationBuilder builder, string name, string path) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class DotnetProjectResource : ExecutableResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource, IResourceWithEnvironment, IResourceWithArgs
    {
        public DotnetProjectResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }
}